/**
 *
 * $Id$
 */
package de.uni_stuttgart.iste.cowolf.model.LqnCore.validation;

import de.uni_stuttgart.iste.cowolf.model.LqnCore.CallOrderType;
import de.uni_stuttgart.iste.cowolf.model.LqnCore.OutputDistributionType;
import de.uni_stuttgart.iste.cowolf.model.LqnCore.OutputResultForwardingANDJoinDelay;
import de.uni_stuttgart.iste.cowolf.model.LqnCore.OutputResultType;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link de.uni_stuttgart.iste.cowolf.model.LqnCore.ActivityDefBase}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ActivityDefBaseValidator {
	boolean validate();

	boolean validateResultJoinDelay(EList<OutputResultForwardingANDJoinDelay> value);
	boolean validateResultForwarding(EList<OutputResultForwardingANDJoinDelay> value);
	boolean validateServiceTimeDistribution(EList<OutputDistributionType> value);
	boolean validateResultActivity(EList<OutputResultType> value);
	boolean validateCallOrder(CallOrderType value);
	boolean validateHostDemandCvsq(Object value);
	boolean validateHostDemandMean(Object value);
	boolean validateMaxServiceTime(Object value);
	boolean validateName(String value);
	boolean validateThinkTime(Object value);
}
