/**
 *
 * $Id$
 */
package de.uni_stuttgart.iste.cowolf.model.LqnCore.validation;

import de.uni_stuttgart.iste.cowolf.model.LqnCore.ActivityMakingCallType;
import de.uni_stuttgart.iste.cowolf.model.LqnCore.CallListType;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.util.FeatureMap;

/**
 * A sample validator interface for {@link de.uni_stuttgart.iste.cowolf.model.LqnCore.ActivityDefType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ActivityDefTypeValidator {
	boolean validate();

	boolean validateCallList(EList<CallListType> value);
	boolean validateGroup(FeatureMap value);
	boolean validateSynchCall(EList<ActivityMakingCallType> value);
	boolean validateAsynchCall(EList<ActivityMakingCallType> value);
	boolean validateBountToType(String value);

	boolean validateBoundToEntry(String value);
}
