/**
 *
 * $Id$
 */
package de.uni_stuttgart.iste.cowolf.model.LqnCore.validation;

import de.uni_stuttgart.iste.cowolf.model.LqnCore.ParameterType;
import de.uni_stuttgart.iste.cowolf.model.LqnCore.PortBindingType;
import de.uni_stuttgart.iste.cowolf.model.LqnCore.ProcessorBindingType;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link de.uni_stuttgart.iste.cowolf.model.LqnCore.BindType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface BindTypeValidator {
	boolean validate();

	boolean validateParameter(EList<ParameterType> value);
	boolean validateProcessorBinding(EList<ProcessorBindingType> value);
	boolean validatePortBinding(EList<PortBindingType> value);
}
