/**
 *
 * $Id$
 */
package de.uni_stuttgart.iste.cowolf.model.LqnCore.validation;

import de.uni_stuttgart.iste.cowolf.model.LqnCore.ActivityListType;
import de.uni_stuttgart.iste.cowolf.model.LqnCore.ActivityLoopListType;
import de.uni_stuttgart.iste.cowolf.model.LqnCore.AndJoinListType;
import de.uni_stuttgart.iste.cowolf.model.LqnCore.OrListType;
import de.uni_stuttgart.iste.cowolf.model.LqnCore.SingleActivityListType;

/**
 * A sample validator interface for {@link de.uni_stuttgart.iste.cowolf.model.LqnCore.PrecedenceType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface PrecedenceTypeValidator {
	boolean validate();

	boolean validatePre(SingleActivityListType value);
	boolean validatePreOR(ActivityListType value);
	boolean validatePreAND(AndJoinListType value);
	boolean validatePost(SingleActivityListType value);
	boolean validatePostOR(OrListType value);
	boolean validatePostAND(ActivityListType value);
	boolean validatePostLOOP(ActivityLoopListType value);
}
