/**
 *
 * $Id$
 */
package de.uni_stuttgart.iste.cowolf.model.component_diagram.validation;

import de.uni_stuttgart.iste.cowolf.model.component_diagram.ComponentInstance;
import de.uni_stuttgart.iste.cowolf.model.component_diagram.ComponentType;
import de.uni_stuttgart.iste.cowolf.model.component_diagram.PortInstance;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link de.uni_stuttgart.iste.cowolf.model.component_diagram.ComponentInstance}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ComponentInstanceValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateSubcomponent(EList<ComponentInstance> value);
	boolean validateParentcomponent(ComponentInstance value);
	boolean validateInPorts(EList<PortInstance> value);
	boolean validateOutPorts(EList<PortInstance> value);
	boolean validateType(ComponentType value);
	boolean validateVersion(int value);
}
