/**
 *
 * $Id$
 */
package de.uni_stuttgart.iste.cowolf.model.component_diagram.validation;

import de.uni_stuttgart.iste.cowolf.model.component_diagram.ComponentInstance;
import de.uni_stuttgart.iste.cowolf.model.component_diagram.PortType;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link de.uni_stuttgart.iste.cowolf.model.component_diagram.ComponentType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ComponentTypeValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validatePort_types(EList<PortType> value);
	boolean validateInstance(EList<ComponentInstance> value);
}
