/*
* generated by Xtext
*/
package de.uni_stuttgart.iste.cowolf.model.ctmc.xtext;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class PCTLStandaloneSetup extends PCTLStandaloneSetupGenerated{

	public static void doSetup() {
		new PCTLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

