/*
 * generated by Xtext
 */
package de.uni_stuttgart.iste.cowolf.model.ctmc.xtext;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class PCTLRuntimeModule extends de.uni_stuttgart.iste.cowolf.model.ctmc.xtext.AbstractPCTLRuntimeModule {

}
