/*
 * generated by Xtext
 */
package de.uni_stuttgart.iste.cowolf.model.dtmc.prism.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ResultUiModule extends de.uni_stuttgart.iste.cowolf.model.dtmc.prism.ui.AbstractResultUiModule {
	public ResultUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
