/*
 * generated by Xtext
 */
package de.uni_stuttgart.iste.cowolf.model.ctmc.xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class PCTLUiModule extends de.uni_stuttgart.iste.cowolf.model.ctmc.xtext.ui.AbstractPCTLUiModule {
	public PCTLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
