/*
* generated by Xtext
*/
package de.uni_stuttgart.iste.cowolf.model.dtmc.prism;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class ResultStandaloneSetup extends ResultStandaloneSetupGenerated{

	public static void doSetup() {
		new ResultStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

