/*
 * generated by Xtext
 */
package de.uni_stuttgart.iste.cowolf.model.dtmc.prism;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ResultRuntimeModule extends de.uni_stuttgart.iste.cowolf.model.dtmc.prism.AbstractResultRuntimeModule {

}
