/*
 * generated by Xtext
 */
package de.uni_stuttgart.iste.cowolf.model.ctmc.xtext.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import de.uni_stuttgart.iste.cowolf.model.ctmc.xtext.ui.internal.PCTLActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class PCTLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return PCTLActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return PCTLActivator.getInstance().getInjector(PCTLActivator.DE_UNI_STUTTGART_ISTE_COWOLF_MODEL_CTMC_XTEXT_PCTL);
	}
	
}
