/**
 * generated by Xtext
 */
package de.uni_stuttgart.iste.cowolf.model.ctmc.xtext.ui.contentassist;

import de.uni_stuttgart.iste.cowolf.model.ctmc.xtext.ui.contentassist.AbstractPCTLProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class PCTLProposalProvider extends AbstractPCTLProposalProvider {
}
