/**
 *
 * $Id$
 */
package de.uni_stuttgart.iste.cowolf.model.statechart.validation;

import de.uni_stuttgart.iste.cowolf.model.statechart.Transition;

/**
 * A sample validator interface for {@link de.uni_stuttgart.iste.cowolf.model.statechart.Guard}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface GuardValidator {
	boolean validate();

	boolean validateExpression(String value);
	boolean validateGua_container(Transition value);
}
