<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="activity" nsURI="http://activity/1.0" nsPrefix="activity">
  <eClassifiers xsi:type="ecore:EClass" name="Root">
    <eStructuralFeatures xsi:type="ecore:EReference" name="start" lowerBound="1" eType="#//Start"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="action" upperBound="-1"
        eType="#//Action" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="decision" upperBound="-1"
        eType="#//Decision" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bar" upperBound="-1" eType="#//Bar"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transition" upperBound="-1"
        eType="#//Arrow" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="end" lowerBound="1" eType="#//End"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="conditionArrow" upperBound="-1"
        eType="#//ConditionArrow" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Start">
    <eStructuralFeatures xsi:type="ecore:EReference" name="outgoingFromStart" lowerBound="1"
        eType="#//Arrow" eOpposite="#//Arrow/fromStart"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Action">
    <eStructuralFeatures xsi:type="ecore:EReference" name="incomingToAction" lowerBound="1"
        upperBound="-1" eType="#//Arrow" eOpposite="#//Arrow/toAction"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Action" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outgoingFromActionAction"
        lowerBound="1" eType="#//Arrow" eOpposite="#//Arrow/fromAction"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="incomingToActionFromDecision"
        lowerBound="1" upperBound="-1" eType="#//ConditionArrow" eOpposite="#//ConditionArrow/toActionFromDecision"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Decision">
    <eStructuralFeatures xsi:type="ecore:EReference" name="outgoingFromDecision" lowerBound="2"
        upperBound="-1" eType="#//ConditionArrow" eOpposite="#//ConditionArrow/fromDecision"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="incomingToDecision" lowerBound="1"
        eType="#//Arrow" eOpposite="#//Arrow/toDecision"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Bar"/>
  <eClassifiers xsi:type="ecore:EClass" name="Split" eSuperTypes="#//Bar">
    <eStructuralFeatures xsi:type="ecore:EReference" name="outgoingFromSplit" lowerBound="2"
        upperBound="-1" eType="#//Arrow" eOpposite="#//Arrow/fromSplit"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="incomingToSplit" lowerBound="1"
        eType="#//Arrow" eOpposite="#//Arrow/toSplit"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Join" eSuperTypes="#//Bar">
    <eStructuralFeatures xsi:type="ecore:EReference" name="incomingToJoin" lowerBound="2"
        upperBound="-1" eType="#//Arrow" eOpposite="#//Arrow/toJoin"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outgoingFromJoin" lowerBound="1"
        eType="#//Arrow" eOpposite="#//Arrow/fromJoin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Arrow">
    <eStructuralFeatures xsi:type="ecore:EReference" name="EReference0" eType="#//Start"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fromStart" eType="#//Start"
        eOpposite="#//Start/outgoingFromStart"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="toEnd" eType="#//End" eOpposite="#//End/incomingToEnd"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fromAction" eType="#//Action"
        eOpposite="#//Action/outgoingFromActionAction"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="toAction" eType="#//Action"
        eOpposite="#//Action/incomingToAction"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fromSplit" eType="#//Split"
        eOpposite="#//Split/outgoingFromSplit"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="toSplit" eType="#//Split"
        eOpposite="#//Split/incomingToSplit"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="toJoin" eType="#//Join"
        eOpposite="#//Join/incomingToJoin"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fromJoin" eType="#//Join"
        eOpposite="#//Join/outgoingFromJoin"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="toDecision" eType="#//Decision"
        eOpposite="#//Decision/incomingToDecision"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="End">
    <eStructuralFeatures xsi:type="ecore:EReference" name="incomingToEnd" lowerBound="1"
        eType="#//Arrow" eOpposite="#//Arrow/toEnd"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConditionArrow">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fromDecision" lowerBound="1"
        eType="#//Decision" eOpposite="#//Decision/outgoingFromDecision"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="toActionFromDecision" lowerBound="1"
        eType="#//Action" eOpposite="#//Action/incomingToActionFromDecision"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="condition" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
