<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="activity" nsURI="http://activity/1.0" nsPrefix="activity">
  <eClassifiers xsi:type="ecore:EClass" name="Root">
    <eStructuralFeatures xsi:type="ecore:EReference" name="start" lowerBound="1" eType="#//Start"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="action" upperBound="-1"
        eType="#//Action" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="decision" upperBound="-1"
        eType="#//Decision" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bar" upperBound="-1" eType="#//Bar"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transition" upperBound="-1"
        eType="#//Transition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="end" lowerBound="1" eType="#//End"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Start">
    <eStructuralFeatures xsi:type="ecore:EReference" name="incoming" eType="#//Transition"
        eOpposite="#//Transition/from"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Action">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Action" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Decision"/>
  <eClassifiers xsi:type="ecore:EClass" name="Bar"/>
  <eClassifiers xsi:type="ecore:EClass" name="Split" eSuperTypes="#//Bar"/>
  <eClassifiers xsi:type="ecore:EClass" name="Join" eSuperTypes="#//Bar"/>
  <eClassifiers xsi:type="ecore:EClass" name="Transition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="condition" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="EReference0" eType="#//Start"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="from" lowerBound="1" eType="#//Start"
        eOpposite="#//Start/incoming"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outgoing" lowerBound="1"
        eType="#//End" eOpposite="#//End/to"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="End">
    <eStructuralFeatures xsi:type="ecore:EReference" name="to" eType="#//Transition"
        eOpposite="#//Transition/outgoing"/>
  </eClassifiers>
</ecore:EPackage>
