/*
* generated by Xtext
*/
package de.uni_stuttgart.iste.cowolf.model.dtmc.prism.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class ResultAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("de/uni_stuttgart/iste/cowolf/model/dtmc/prism/parser/antlr/internal/InternalResult.tokens");
	}
}
