<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ModelAssociation" nsURI="http://cowolf.model_association/" nsPrefix="ModelAssociation">
  <eAnnotations source="http://www.eclipse.org/OCL/Import">
    <details key="ecore" value="http://www.eclipse.org/emf/2002/Ecore"/>
    <details key="trace" value="../../org.eclipse.emf.henshin.trace/model/trace.ecore#/"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="ModelAssociation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="models" upperBound="-1"
        eType="#//Model" containment="true" eOpposite="#//Model/parent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="associations" upperBound="-1"
        eType="#//Association" eOpposite="#//Association/parent"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Model">
    <eStructuralFeatures xsi:type="ecore:EReference" name="versions" upperBound="-1"
        eType="#//ModelVersion" containment="true" eOpposite="#//ModelVersion/model"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="model" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="modelID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//ModelAssociation"
        eOpposite="#//ModelAssociation/models"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Association">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        upperBound="-1" eType="#//ModelVersion" eOpposite="#//ModelVersion/sourceAssociations"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        upperBound="-1" eType="#//ModelVersion" eOpposite="#//ModelVersion/targetAssociations"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="traces" upperBound="-1"
        eType="ecore:EClass ../../org.eclipse.emf.henshin.trace/model/trace.ecore#//Trace"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="timestamp" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//ModelAssociation"
        eOpposite="#//ModelAssociation/associations"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModelVersion">
    <eStructuralFeatures xsi:type="ecore:EReference" name="model" eType="#//Model"
        eOpposite="#//Model/versions"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="timestamp" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="current" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="manual" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetAssociations" upperBound="-1"
        eType="#//Association" eOpposite="#//Association/target"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceAssociations" upperBound="-1"
        eType="#//Association" eOpposite="#//Association/source"/>
  </eClassifiers>
</ecore:EPackage>
