<?xml version="1.0" encoding="ISO-8859-1"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="Statechart" nsURI="http://Statechart/1.0" nsPrefix="statechart">
  <eClassifiers xsi:type="ecore:EClass" name="BooleanExpression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StateMachine">
    <eStructuralFeatures xsi:type="ecore:EReference" name="transitions" ordered="false"
        upperBound="-1" eType="#//Transition" containment="true" eOpposite="#//Transition/transSM_container"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="top" ordered="false" upperBound="-1"
        eType="#//State" containment="true" eOpposite="#//State/state_container"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="State" eSuperTypes="#//StateVertex">
    <eStructuralFeatures xsi:type="ecore:EReference" name="state_container" ordered="false"
        lowerBound="1" eType="#//StateMachine" eOpposite="#//StateMachine/top"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="internalTransitions" ordered="false"
        upperBound="-1" eType="#//Transition" containment="true" eOpposite="#//Transition/transS_container"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="deferrableEvents" ordered="false"
        upperBound="-1" eType="#//Event" eOpposite="#//Event/targets"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CompositeState" eSuperTypes="#//State">
    <eStructuralFeatures xsi:type="ecore:EReference" name="subVertexes" ordered="false"
        upperBound="-1" eType="#//StateVertex" containment="true" eOpposite="#//StateVertex/sv_container"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isConcurrent" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Transition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="transSM_container" ordered="false"
        eType="#//StateMachine" eOpposite="#//StateMachine/transitions"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transS_container" ordered="false"
        eType="#//State" eOpposite="#//State/internalTransitions"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="trigger" ordered="false"
        eType="#//Event" eOpposite="#//Event/evt_container"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="guard" ordered="false"
        eType="#//Guard" containment="true" eOpposite="#//Guard/gua_container"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" ordered="false"
        lowerBound="1" eType="#//StateVertex" eOpposite="#//StateVertex/outgoing"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" ordered="false"
        lowerBound="1" eType="#//StateVertex" eOpposite="#//StateVertex/incoming"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StateVertex">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sv_container" ordered="false"
        eType="#//CompositeState" eOpposite="#//CompositeState/subVertexes"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outgoing" ordered="false"
        upperBound="-1" eType="#//Transition" eOpposite="#//Transition/source"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="incoming" ordered="false"
        upperBound="-1" eType="#//Transition" eOpposite="#//Transition/target"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true">
      <eAnnotations source="ExtendedMetaData">
        <details key="name" value="id"/>
        <details key="namespace" value="http://sdq.ipd.uka.de/Indentifier/1.0"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Guard">
    <eStructuralFeatures xsi:type="ecore:EReference" name="gua_container" ordered="false"
        lowerBound="1" eType="#//Transition" eOpposite="#//Transition/guard"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" ordered="false"
        lowerBound="1" eType="#//BooleanExpression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Event">
    <eStructuralFeatures xsi:type="ecore:EReference" name="evt_container" ordered="false"
        upperBound="-1" eType="#//Transition" eOpposite="#//Transition/trigger"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targets" ordered="false"
        upperBound="-1" eType="#//State" eOpposite="#//State/deferrableEvents"/>
  </eClassifiers>
</ecore:EPackage>
