<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="sequence" nsURI="sequence" nsPrefix="sequence">
  <eClassifiers xsi:type="ecore:EClass" name="Sequence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="element" upperBound="-1"
        eType="#//Element" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="block" upperBound="-1"
        eType="#//Block" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Element" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Lifeline" eSuperTypes="#//Element">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="task" upperBound="-1" eType="#//Task"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Message" eSuperTypes="#//Element">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="MessageKind" eType="#//MessageKind"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="MessageSort" eType="#//MessageSort"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="from" lowerBound="1" eType="#//Task"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="to" lowerBound="1" eType="#//Task"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Task">
    <eStructuralFeatures xsi:type="ecore:EReference" name="outgoing" upperBound="-1"
        eType="#//Message" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="incoming" upperBound="-1"
        eType="#//Message"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="MessageKind">
    <eLiterals name="complete" literal="complete"/>
    <eLiterals name="lost" value="1" literal="lost"/>
    <eLiterals name="found" value="2" literal="found"/>
    <eLiterals name="unknown" value="3" literal="unknown"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="MessageSort">
    <eLiterals name="synchCall" literal="synchCall"/>
    <eLiterals name="asynchCall" value="1" literal="asynchCall"/>
    <eLiterals name="asynchSignal" value="2" literal="asynchSignal"/>
    <eLiterals name="createMessage" value="3" literal="createMessage"/>
    <eLiterals name="deleteMessage" value="4" literal="deleteMessage"/>
    <eLiterals name="reply" value="5" literal="reply"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Block"/>
  <eClassifiers xsi:type="ecore:EClass" name="LoopBlock" eSuperTypes="#//Block">
    <eStructuralFeatures xsi:type="ecore:EReference" name="include" upperBound="-1"
        eType="#//Element" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AltBlock" eSuperTypes="#//Block">
    <eStructuralFeatures xsi:type="ecore:EReference" name="alternative" lowerBound="2"
        upperBound="-1" eType="#//Alternative" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Alternative">
    <eStructuralFeatures xsi:type="ecore:EReference" name="includes" upperBound="-1"
        eType="#//Element" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
