<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="fault_tree" nsURI="http://FaultTree/1.0" nsPrefix="fault_tree">
  <eAnnotations source="http://www.eclipse.org/OCL/Import">
    <details key="ecore" value="http://www.eclipse.org/emf/2002/Ecore"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Hazard" eSuperTypes="#//Event">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="NoStandaloneUndevelopedEvent"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="NoStandaloneUndevelopedEvent" value="self.inputGate->size() + self.outputGate->size() + self.inEvent->size() > 0"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inEvent" eType="#//IntermediateEvent"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Gate" abstract="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="NoHazardAsInput NoBasicEventAsOutput AtLeastTwoInputs ExactlyOneOutput"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="NoHazardAsInput" value="self.inputEvents->forAll(e : Event | (e.oclIsTypeOf(BasicEvent) or e.oclIsTypeOf(IntermediateEvent)) and not e.oclIsTypeOf(Hazard))"/>
      <details key="NoBasicEventAsOutput" value="self.outputEvent->forAll(e : Event | (e.oclIsTypeOf(IntermediateEvent) or e.oclIsTypeOf(Hazard)) and not e.oclIsTypeOf(BasicEvent))"/>
      <details key="AtLeastTwoInputs" value="self.inputGates->size() + self.inputEvents->size() >= 2"/>
      <details key="ExactlyOneOutput" value="self.outputGate->size() + self.outputEvent->size() = 1"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputGates" upperBound="-1"
        eType="#//Gate"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputEvents" upperBound="-1"
        eType="#//Event" eOpposite="#//Event/outputGate"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outputGate" eType="#//Gate"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outputEvent" eType="#//Event"
        eOpposite="#//Event/inputGate"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="root" eType="#//Root" eOpposite="#//Root/gate"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Event" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputGate" eType="#//Gate"
        eOpposite="#//Gate/outputEvent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outputGate" eType="#//Gate"
        eOpposite="#//Gate/inputEvents"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="root" eType="#//Root" eOpposite="#//Root/event"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntermediateEvent" eSuperTypes="#//Event">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="OnlyIntermediateOrBasicEventAsInput NoStandaloneIntermediateEvent OnlyIntermediateOrHazardtAsOutput"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="OnlyIntermediateOrBasicEventAsInput" value="self.inEvent->forAll(e : Event | (e.oclIsTypeOf(IntermediateEvent) or e.oclIsTypeOf(BasicEvent)))"/>
      <details key="NoStandaloneIntermediateEvent" value="self.inputGate->size() + self.outputGate->size() + self.inEvent->size() + self.outEvent->size()> 0"/>
      <details key="OnlyIntermediateOrHazardtAsOutput" value="self.outEvent->forAll(e : Event | (e.oclIsTypeOf(IntermediateEvent) or e.oclIsTypeOf(Hazard)))"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="instance" upperBound="-1"
        eType="#//FailureInstance" eOpposite="#//FailureInstance/event"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inEvent" eType="#//Event"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outEvent" eType="#//Event"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FailureType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="instance" lowerBound="1"
        upperBound="-1" eType="#//FailureInstance" eOpposite="#//FailureInstance/type"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="root" eType="#//Root" eOpposite="#//Root/failure_type"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FailureInstance">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//FailureType"
        eOpposite="#//FailureType/instance"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="root" eType="#//Root" eOpposite="#//Root/failure_instance"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="previousFailure" eType="#//FailureInstance"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="previousError" eType="#//ErrorInstance"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="event" eType="#//IntermediateEvent"
        eOpposite="#//IntermediateEvent/instance"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BasicEvent" eSuperTypes="#//Event">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="NoStandaloneBasicEvent"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="NoStandaloneBasicEvent" value="self.inputGate->size() + self.outputGate->size() + self.outEvent->size()> 0"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="instance" upperBound="-1"
        eType="#//ErrorInstance" eOpposite="#//ErrorInstance/error"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="probability" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outEvent" eType="#//IntermediateEvent"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UndevelopedEvent" eSuperTypes="#//Event">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="NoStandaloneUndevelopedEvent"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="NoStandaloneUndevelopedEvent" value="self.inputGate->size() + self.outputGate->size() > 0"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ErrorType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="error" lowerBound="1" upperBound="-1"
        eType="#//ErrorInstance" eOpposite="#//ErrorInstance/type"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="root" eType="#//Root" eOpposite="#//Root/error_type"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ErrorInstance">
    <eStructuralFeatures xsi:type="ecore:EReference" name="error" eType="#//BasicEvent"
        eOpposite="#//BasicEvent/instance"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//ErrorType"
        eOpposite="#//ErrorType/error"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="root" eType="#//Root" eOpposite="#//Root/error_instance"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OR" eSuperTypes="#//Gate"/>
  <eClassifiers xsi:type="ecore:EClass" name="AND" eSuperTypes="#//Gate"/>
  <eClassifiers xsi:type="ecore:EClass" name="XOR" eSuperTypes="#//Gate"/>
  <eClassifiers xsi:type="ecore:EClass" name="PriorAND" eSuperTypes="#//Gate"/>
  <eClassifiers xsi:type="ecore:EClass" name="Inhibit" eSuperTypes="#//Gate"/>
  <eClassifiers xsi:type="ecore:EClass" name="Root">
    <eStructuralFeatures xsi:type="ecore:EReference" name="hazard" lowerBound="1"
        eType="#//Hazard" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="gate" upperBound="-1" eType="#//Gate"
        containment="true" eOpposite="#//Gate/root"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="event" upperBound="-1"
        eType="#//Event" containment="true" eOpposite="#//Event/root"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="failure_instance" upperBound="-1"
        eType="#//FailureInstance" containment="true" eOpposite="#//FailureInstance/root"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="failure_type" upperBound="-1"
        eType="#//FailureType" containment="true" eOpposite="#//FailureType/root"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="error_instance" upperBound="-1"
        eType="#//ErrorInstance" containment="true" eOpposite="#//ErrorInstance/root"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="error_type" upperBound="-1"
        eType="#//ErrorType" containment="true" eOpposite="#//ErrorType/root"/>
  </eClassifiers>
</ecore:EPackage>
