/*
* generated by Xtext
*/
package de.uni_stuttgart.iste.cowolf.model.ctmc.xtext.services;

import com.google.inject.Singleton;
import com.google.inject.Inject;

import java.util.List;

import org.eclipse.xtext.*;
import org.eclipse.xtext.service.GrammarProvider;
import org.eclipse.xtext.service.AbstractElementFinder.*;

import org.eclipse.xtext.common.services.TerminalsGrammarAccess;

@Singleton
public class PCTLGrammarAccess extends AbstractGrammarElementFinder {
	
	
	public class StartElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Start");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Assignment cStartAssignment_0 = (Assignment)cAlternatives.eContents().get(0);
		private final RuleCall cStartSParserRuleCall_0_0 = (RuleCall)cStartAssignment_0.eContents().get(0);
		private final RuleCall cPParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cPGParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		
		//Start:
		//	start=S | P | PG;
		public ParserRule getRule() { return rule; }

		//start=S | P | PG
		public Alternatives getAlternatives() { return cAlternatives; }

		//start=S
		public Assignment getStartAssignment_0() { return cStartAssignment_0; }

		//S
		public RuleCall getStartSParserRuleCall_0_0() { return cStartSParserRuleCall_0_0; }

		//P
		public RuleCall getPParserRuleCall_1() { return cPParserRuleCall_1; }

		//PG
		public RuleCall getPGParserRuleCall_2() { return cPGParserRuleCall_2; }
	}

	public class StateElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "State");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cAlternatives.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_0_0 = (Keyword)cGroup_0.eContents().get(0);
		private final Keyword cStateKeyword_0_1 = (Keyword)cGroup_0.eContents().get(1);
		private final Assignment cNameAssignment_0_2 = (Assignment)cGroup_0.eContents().get(2);
		private final RuleCall cNameIDTerminalRuleCall_0_2_0 = (RuleCall)cNameAssignment_0_2.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_0_3 = (Keyword)cGroup_0.eContents().get(3);
		private final Group cGroup_1 = (Group)cAlternatives.eContents().get(1);
		private final Keyword cStateKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Assignment cNameAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_1_0 = (RuleCall)cNameAssignment_1_1.eContents().get(0);
		
		//State:
		//	"(" "State:" name=ID ")" | "State:" name=ID;
		public ParserRule getRule() { return rule; }

		//"(" "State:" name=ID ")" | "State:" name=ID
		public Alternatives getAlternatives() { return cAlternatives; }

		//"(" "State:" name=ID ")"
		public Group getGroup_0() { return cGroup_0; }

		//"("
		public Keyword getLeftParenthesisKeyword_0_0() { return cLeftParenthesisKeyword_0_0; }

		//"State:"
		public Keyword getStateKeyword_0_1() { return cStateKeyword_0_1; }

		//name=ID
		public Assignment getNameAssignment_0_2() { return cNameAssignment_0_2; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_0_2_0() { return cNameIDTerminalRuleCall_0_2_0; }

		//")"
		public Keyword getRightParenthesisKeyword_0_3() { return cRightParenthesisKeyword_0_3; }

		//"State:" name=ID
		public Group getGroup_1() { return cGroup_1; }

		//"State:"
		public Keyword getStateKeyword_1_0() { return cStateKeyword_1_0; }

		//name=ID
		public Assignment getNameAssignment_1_1() { return cNameAssignment_1_1; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_1_1_0() { return cNameIDTerminalRuleCall_1_1_0; }
	}

	public class LabelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Label");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cAlternatives.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_0_0 = (Keyword)cGroup_0.eContents().get(0);
		private final Keyword cLabelKeyword_0_1 = (Keyword)cGroup_0.eContents().get(1);
		private final Assignment cNameAssignment_0_2 = (Assignment)cGroup_0.eContents().get(2);
		private final RuleCall cNameIDTerminalRuleCall_0_2_0 = (RuleCall)cNameAssignment_0_2.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_0_3 = (Keyword)cGroup_0.eContents().get(3);
		private final Group cGroup_1 = (Group)cAlternatives.eContents().get(1);
		private final Keyword cLabelKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Assignment cNameAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_1_0 = (RuleCall)cNameAssignment_1_1.eContents().get(0);
		
		//Label:
		//	"(" "Label:" name=ID ")" | "Label:" name=ID;
		public ParserRule getRule() { return rule; }

		//"(" "Label:" name=ID ")" | "Label:" name=ID
		public Alternatives getAlternatives() { return cAlternatives; }

		//"(" "Label:" name=ID ")"
		public Group getGroup_0() { return cGroup_0; }

		//"("
		public Keyword getLeftParenthesisKeyword_0_0() { return cLeftParenthesisKeyword_0_0; }

		//"Label:"
		public Keyword getLabelKeyword_0_1() { return cLabelKeyword_0_1; }

		//name=ID
		public Assignment getNameAssignment_0_2() { return cNameAssignment_0_2; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_0_2_0() { return cNameIDTerminalRuleCall_0_2_0; }

		//")"
		public Keyword getRightParenthesisKeyword_0_3() { return cRightParenthesisKeyword_0_3; }

		//"Label:" name=ID
		public Group getGroup_1() { return cGroup_1; }

		//"Label:"
		public Keyword getLabelKeyword_1_0() { return cLabelKeyword_1_0; }

		//name=ID
		public Assignment getNameAssignment_1_1() { return cNameAssignment_1_1; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_1_1_0() { return cNameIDTerminalRuleCall_1_1_0; }
	}

	public class StateOrLabelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "StateOrLabel");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cStateParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cLabelParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//StateOrLabel:
		//	State | Label;
		public ParserRule getRule() { return rule; }

		//State | Label
		public Alternatives getAlternatives() { return cAlternatives; }

		//State
		public RuleCall getStateParserRuleCall_0() { return cStateParserRuleCall_0; }

		//Label
		public RuleCall getLabelParserRuleCall_1() { return cLabelParserRuleCall_1; }
	}

	public class SElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "S");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cSKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cCompareParserRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		private final Keyword cLeftSquareBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final RuleCall cStateOrLabelParserRuleCall_3 = (RuleCall)cGroup.eContents().get(3);
		private final Keyword cRightSquareBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//S:
		//	"S" Compare "[" StateOrLabel "]";
		public ParserRule getRule() { return rule; }

		//"S" Compare "[" StateOrLabel "]"
		public Group getGroup() { return cGroup; }

		//"S"
		public Keyword getSKeyword_0() { return cSKeyword_0; }

		//Compare
		public RuleCall getCompareParserRuleCall_1() { return cCompareParserRuleCall_1; }

		//"["
		public Keyword getLeftSquareBracketKeyword_2() { return cLeftSquareBracketKeyword_2; }

		//StateOrLabel
		public RuleCall getStateOrLabelParserRuleCall_3() { return cStateOrLabelParserRuleCall_3; }

		//"]"
		public Keyword getRightSquareBracketKeyword_4() { return cRightSquareBracketKeyword_4; }
	}

	public class PElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "P");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cAlternatives.eContents().get(0);
		private final Keyword cPKeyword_0_0 = (Keyword)cGroup_0.eContents().get(0);
		private final RuleCall cCompareParserRuleCall_0_1 = (RuleCall)cGroup_0.eContents().get(1);
		private final Keyword cLeftSquareBracketKeyword_0_2 = (Keyword)cGroup_0.eContents().get(2);
		private final Keyword cFKeyword_0_3 = (Keyword)cGroup_0.eContents().get(3);
		private final RuleCall cTimeBoundParserRuleCall_0_4 = (RuleCall)cGroup_0.eContents().get(4);
		private final RuleCall cStateOrLabelParserRuleCall_0_5 = (RuleCall)cGroup_0.eContents().get(5);
		private final Keyword cRightSquareBracketKeyword_0_6 = (Keyword)cGroup_0.eContents().get(6);
		private final Group cGroup_1 = (Group)cAlternatives.eContents().get(1);
		private final Keyword cPKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final RuleCall cCompareParserRuleCall_1_1 = (RuleCall)cGroup_1.eContents().get(1);
		private final Keyword cLeftSquareBracketKeyword_1_2 = (Keyword)cGroup_1.eContents().get(2);
		private final Assignment cLEFTAssignment_1_3 = (Assignment)cGroup_1.eContents().get(3);
		private final RuleCall cLEFTStateOrLabelParserRuleCall_1_3_0 = (RuleCall)cLEFTAssignment_1_3.eContents().get(0);
		private final Keyword cUKeyword_1_4 = (Keyword)cGroup_1.eContents().get(4);
		private final RuleCall cTimeBoundParserRuleCall_1_5 = (RuleCall)cGroup_1.eContents().get(5);
		private final Assignment cRIGHTAssignment_1_6 = (Assignment)cGroup_1.eContents().get(6);
		private final RuleCall cRIGHTStateOrLabelParserRuleCall_1_6_0 = (RuleCall)cRIGHTAssignment_1_6.eContents().get(0);
		private final Keyword cRightSquareBracketKeyword_1_7 = (Keyword)cGroup_1.eContents().get(7);
		
		//P:
		//	"P" Compare "[" "F" TimeBound StateOrLabel "]" | "P" Compare "[" LEFT=StateOrLabel "U" TimeBound RIGHT=StateOrLabel
		//	"]";
		public ParserRule getRule() { return rule; }

		//"P" Compare "[" "F" TimeBound StateOrLabel "]" | "P" Compare "[" LEFT=StateOrLabel "U" TimeBound RIGHT=StateOrLabel "]"
		public Alternatives getAlternatives() { return cAlternatives; }

		//"P" Compare "[" "F" TimeBound StateOrLabel "]"
		public Group getGroup_0() { return cGroup_0; }

		//"P"
		public Keyword getPKeyword_0_0() { return cPKeyword_0_0; }

		//Compare
		public RuleCall getCompareParserRuleCall_0_1() { return cCompareParserRuleCall_0_1; }

		//"["
		public Keyword getLeftSquareBracketKeyword_0_2() { return cLeftSquareBracketKeyword_0_2; }

		//"F"
		public Keyword getFKeyword_0_3() { return cFKeyword_0_3; }

		//TimeBound
		public RuleCall getTimeBoundParserRuleCall_0_4() { return cTimeBoundParserRuleCall_0_4; }

		//StateOrLabel
		public RuleCall getStateOrLabelParserRuleCall_0_5() { return cStateOrLabelParserRuleCall_0_5; }

		//"]"
		public Keyword getRightSquareBracketKeyword_0_6() { return cRightSquareBracketKeyword_0_6; }

		//"P" Compare "[" LEFT=StateOrLabel "U" TimeBound RIGHT=StateOrLabel "]"
		public Group getGroup_1() { return cGroup_1; }

		//"P"
		public Keyword getPKeyword_1_0() { return cPKeyword_1_0; }

		//Compare
		public RuleCall getCompareParserRuleCall_1_1() { return cCompareParserRuleCall_1_1; }

		//"["
		public Keyword getLeftSquareBracketKeyword_1_2() { return cLeftSquareBracketKeyword_1_2; }

		//LEFT=StateOrLabel
		public Assignment getLEFTAssignment_1_3() { return cLEFTAssignment_1_3; }

		//StateOrLabel
		public RuleCall getLEFTStateOrLabelParserRuleCall_1_3_0() { return cLEFTStateOrLabelParserRuleCall_1_3_0; }

		//"U"
		public Keyword getUKeyword_1_4() { return cUKeyword_1_4; }

		//TimeBound
		public RuleCall getTimeBoundParserRuleCall_1_5() { return cTimeBoundParserRuleCall_1_5; }

		//RIGHT=StateOrLabel
		public Assignment getRIGHTAssignment_1_6() { return cRIGHTAssignment_1_6; }

		//StateOrLabel
		public RuleCall getRIGHTStateOrLabelParserRuleCall_1_6_0() { return cRIGHTStateOrLabelParserRuleCall_1_6_0; }

		//"]"
		public Keyword getRightSquareBracketKeyword_1_7() { return cRightSquareBracketKeyword_1_7; }
	}

	public class PGElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "PG");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cPKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cCompareParserRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		private final Keyword cLeftSquareBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cGKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cLeftParenthesisKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cLEFTAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cLEFTStateOrLabelParserRuleCall_5_0 = (RuleCall)cLEFTAssignment_5.eContents().get(0);
		private final Keyword cEqualsSignGreaterThanSignKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Keyword cPKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final RuleCall cCompareWithoutUnknownParserRuleCall_8 = (RuleCall)cGroup.eContents().get(8);
		private final Keyword cLeftSquareBracketKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Keyword cFKeyword_10 = (Keyword)cGroup.eContents().get(10);
		private final RuleCall cTimeBoundParserRuleCall_11 = (RuleCall)cGroup.eContents().get(11);
		private final Assignment cRIGHTAssignment_12 = (Assignment)cGroup.eContents().get(12);
		private final RuleCall cRIGHTStateOrLabelParserRuleCall_12_0 = (RuleCall)cRIGHTAssignment_12.eContents().get(0);
		private final Keyword cRightSquareBracketKeyword_13 = (Keyword)cGroup.eContents().get(13);
		private final Keyword cRightParenthesisKeyword_14 = (Keyword)cGroup.eContents().get(14);
		private final Keyword cRightSquareBracketKeyword_15 = (Keyword)cGroup.eContents().get(15);
		
		//PG:
		//	"P" Compare "[" "G" "(" LEFT=StateOrLabel "=>" "P" CompareWithoutUnknown "[" "F" TimeBound RIGHT=StateOrLabel "]" ")"
		//	"]";
		public ParserRule getRule() { return rule; }

		//"P" Compare "[" "G" "(" LEFT=StateOrLabel "=>" "P" CompareWithoutUnknown "[" "F" TimeBound RIGHT=StateOrLabel "]" ")"
		//"]"
		public Group getGroup() { return cGroup; }

		//"P"
		public Keyword getPKeyword_0() { return cPKeyword_0; }

		//Compare
		public RuleCall getCompareParserRuleCall_1() { return cCompareParserRuleCall_1; }

		//"["
		public Keyword getLeftSquareBracketKeyword_2() { return cLeftSquareBracketKeyword_2; }

		//"G"
		public Keyword getGKeyword_3() { return cGKeyword_3; }

		//"("
		public Keyword getLeftParenthesisKeyword_4() { return cLeftParenthesisKeyword_4; }

		//LEFT=StateOrLabel
		public Assignment getLEFTAssignment_5() { return cLEFTAssignment_5; }

		//StateOrLabel
		public RuleCall getLEFTStateOrLabelParserRuleCall_5_0() { return cLEFTStateOrLabelParserRuleCall_5_0; }

		//"=>"
		public Keyword getEqualsSignGreaterThanSignKeyword_6() { return cEqualsSignGreaterThanSignKeyword_6; }

		//"P"
		public Keyword getPKeyword_7() { return cPKeyword_7; }

		//CompareWithoutUnknown
		public RuleCall getCompareWithoutUnknownParserRuleCall_8() { return cCompareWithoutUnknownParserRuleCall_8; }

		//"["
		public Keyword getLeftSquareBracketKeyword_9() { return cLeftSquareBracketKeyword_9; }

		//"F"
		public Keyword getFKeyword_10() { return cFKeyword_10; }

		//TimeBound
		public RuleCall getTimeBoundParserRuleCall_11() { return cTimeBoundParserRuleCall_11; }

		//RIGHT=StateOrLabel
		public Assignment getRIGHTAssignment_12() { return cRIGHTAssignment_12; }

		//StateOrLabel
		public RuleCall getRIGHTStateOrLabelParserRuleCall_12_0() { return cRIGHTStateOrLabelParserRuleCall_12_0; }

		//"]"
		public Keyword getRightSquareBracketKeyword_13() { return cRightSquareBracketKeyword_13; }

		//")"
		public Keyword getRightParenthesisKeyword_14() { return cRightParenthesisKeyword_14; }

		//"]"
		public Keyword getRightSquareBracketKeyword_15() { return cRightSquareBracketKeyword_15; }
	}

	public class CompareElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Compare");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cCompareWithoutUnknownParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final Keyword cEqualsSignQuestionMarkKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		
		//Compare:
		//	CompareWithoutUnknown | "=?";
		public ParserRule getRule() { return rule; }

		//CompareWithoutUnknown | "=?"
		public Alternatives getAlternatives() { return cAlternatives; }

		//CompareWithoutUnknown
		public RuleCall getCompareWithoutUnknownParserRuleCall_0() { return cCompareWithoutUnknownParserRuleCall_0; }

		//"=?"
		public Keyword getEqualsSignQuestionMarkKeyword_1() { return cEqualsSignQuestionMarkKeyword_1; }
	}

	public class CompareWithoutUnknownElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "CompareWithoutUnknown");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cAlternatives.eContents().get(0);
		private final Keyword cGreaterThanSignKeyword_0_0 = (Keyword)cGroup_0.eContents().get(0);
		private final RuleCall cDECIMALParserRuleCall_0_1 = (RuleCall)cGroup_0.eContents().get(1);
		private final Group cGroup_1 = (Group)cAlternatives.eContents().get(1);
		private final Keyword cLessThanSignKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final RuleCall cDECIMALParserRuleCall_1_1 = (RuleCall)cGroup_1.eContents().get(1);
		private final Group cGroup_2 = (Group)cAlternatives.eContents().get(2);
		private final Keyword cGreaterThanSignEqualsSignKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final RuleCall cDECIMALParserRuleCall_2_1 = (RuleCall)cGroup_2.eContents().get(1);
		private final Group cGroup_3 = (Group)cAlternatives.eContents().get(3);
		private final Keyword cLessThanSignEqualsSignKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final RuleCall cDECIMALParserRuleCall_3_1 = (RuleCall)cGroup_3.eContents().get(1);
		
		//CompareWithoutUnknown:
		//	">" DECIMAL | "<" DECIMAL | ">=" DECIMAL | "<=" DECIMAL;
		public ParserRule getRule() { return rule; }

		//">" DECIMAL | "<" DECIMAL | ">=" DECIMAL | "<=" DECIMAL
		public Alternatives getAlternatives() { return cAlternatives; }

		//">" DECIMAL
		public Group getGroup_0() { return cGroup_0; }

		//">"
		public Keyword getGreaterThanSignKeyword_0_0() { return cGreaterThanSignKeyword_0_0; }

		//DECIMAL
		public RuleCall getDECIMALParserRuleCall_0_1() { return cDECIMALParserRuleCall_0_1; }

		//"<" DECIMAL
		public Group getGroup_1() { return cGroup_1; }

		//"<"
		public Keyword getLessThanSignKeyword_1_0() { return cLessThanSignKeyword_1_0; }

		//DECIMAL
		public RuleCall getDECIMALParserRuleCall_1_1() { return cDECIMALParserRuleCall_1_1; }

		//">=" DECIMAL
		public Group getGroup_2() { return cGroup_2; }

		//">="
		public Keyword getGreaterThanSignEqualsSignKeyword_2_0() { return cGreaterThanSignEqualsSignKeyword_2_0; }

		//DECIMAL
		public RuleCall getDECIMALParserRuleCall_2_1() { return cDECIMALParserRuleCall_2_1; }

		//"<=" DECIMAL
		public Group getGroup_3() { return cGroup_3; }

		//"<="
		public Keyword getLessThanSignEqualsSignKeyword_3_0() { return cLessThanSignEqualsSignKeyword_3_0; }

		//DECIMAL
		public RuleCall getDECIMALParserRuleCall_3_1() { return cDECIMALParserRuleCall_3_1; }
	}

	public class TimeBoundElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "TimeBound");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cAlternatives.eContents().get(0);
		private final Keyword cGreaterThanSignEqualsSignKeyword_0_0 = (Keyword)cGroup_0.eContents().get(0);
		private final RuleCall cDECIMALParserRuleCall_0_1 = (RuleCall)cGroup_0.eContents().get(1);
		private final Group cGroup_1 = (Group)cAlternatives.eContents().get(1);
		private final Keyword cLessThanSignEqualsSignKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final RuleCall cDECIMALParserRuleCall_1_1 = (RuleCall)cGroup_1.eContents().get(1);
		private final Group cGroup_2 = (Group)cAlternatives.eContents().get(2);
		private final Keyword cLeftSquareBracketKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final RuleCall cDECIMALParserRuleCall_2_1 = (RuleCall)cGroup_2.eContents().get(1);
		private final Keyword cCommaKeyword_2_2 = (Keyword)cGroup_2.eContents().get(2);
		private final RuleCall cDECIMALParserRuleCall_2_3 = (RuleCall)cGroup_2.eContents().get(3);
		private final Keyword cRightSquareBracketKeyword_2_4 = (Keyword)cGroup_2.eContents().get(4);
		
		//TimeBound:
		//	(">=" DECIMAL | "<=" DECIMAL | "[" DECIMAL "," DECIMAL "]")?;
		public ParserRule getRule() { return rule; }

		//(">=" DECIMAL | "<=" DECIMAL | "[" DECIMAL "," DECIMAL "]")?
		public Alternatives getAlternatives() { return cAlternatives; }

		//">=" DECIMAL
		public Group getGroup_0() { return cGroup_0; }

		//">="
		public Keyword getGreaterThanSignEqualsSignKeyword_0_0() { return cGreaterThanSignEqualsSignKeyword_0_0; }

		//DECIMAL
		public RuleCall getDECIMALParserRuleCall_0_1() { return cDECIMALParserRuleCall_0_1; }

		//"<=" DECIMAL
		public Group getGroup_1() { return cGroup_1; }

		//"<="
		public Keyword getLessThanSignEqualsSignKeyword_1_0() { return cLessThanSignEqualsSignKeyword_1_0; }

		//DECIMAL
		public RuleCall getDECIMALParserRuleCall_1_1() { return cDECIMALParserRuleCall_1_1; }

		//"[" DECIMAL "," DECIMAL "]"
		public Group getGroup_2() { return cGroup_2; }

		//"["
		public Keyword getLeftSquareBracketKeyword_2_0() { return cLeftSquareBracketKeyword_2_0; }

		//DECIMAL
		public RuleCall getDECIMALParserRuleCall_2_1() { return cDECIMALParserRuleCall_2_1; }

		//","
		public Keyword getCommaKeyword_2_2() { return cCommaKeyword_2_2; }

		//DECIMAL
		public RuleCall getDECIMALParserRuleCall_2_3() { return cDECIMALParserRuleCall_2_3; }

		//"]"
		public Keyword getRightSquareBracketKeyword_2_4() { return cRightSquareBracketKeyword_2_4; }
	}

	public class DECIMALElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "DECIMAL");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cINTTerminalRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cFullStopKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1_1 = (RuleCall)cGroup_1.eContents().get(1);
		
		//DECIMAL:
		//	INT ("." INT)?;
		public ParserRule getRule() { return rule; }

		//INT ("." INT)?
		public Group getGroup() { return cGroup; }

		//INT
		public RuleCall getINTTerminalRuleCall_0() { return cINTTerminalRuleCall_0; }

		//("." INT)?
		public Group getGroup_1() { return cGroup_1; }

		//"."
		public Keyword getFullStopKeyword_1_0() { return cFullStopKeyword_1_0; }

		//INT
		public RuleCall getINTTerminalRuleCall_1_1() { return cINTTerminalRuleCall_1_1; }
	}
	
	
	private StartElements pStart;
	private StateElements pState;
	private LabelElements pLabel;
	private StateOrLabelElements pStateOrLabel;
	private SElements pS;
	private PElements pP;
	private PGElements pPG;
	private CompareElements pCompare;
	private CompareWithoutUnknownElements pCompareWithoutUnknown;
	private TimeBoundElements pTimeBound;
	private DECIMALElements pDECIMAL;
	
	private final Grammar grammar;

	private TerminalsGrammarAccess gaTerminals;

	@Inject
	public PCTLGrammarAccess(GrammarProvider grammarProvider,
		TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("de.uni_stuttgart.iste.cowolf.model.ctmc.xtext.PCTL".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	
	public Grammar getGrammar() {
		return grammar;
	}
	

	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Start:
	//	start=S | P | PG;
	public StartElements getStartAccess() {
		return (pStart != null) ? pStart : (pStart = new StartElements());
	}
	
	public ParserRule getStartRule() {
		return getStartAccess().getRule();
	}

	//State:
	//	"(" "State:" name=ID ")" | "State:" name=ID;
	public StateElements getStateAccess() {
		return (pState != null) ? pState : (pState = new StateElements());
	}
	
	public ParserRule getStateRule() {
		return getStateAccess().getRule();
	}

	//Label:
	//	"(" "Label:" name=ID ")" | "Label:" name=ID;
	public LabelElements getLabelAccess() {
		return (pLabel != null) ? pLabel : (pLabel = new LabelElements());
	}
	
	public ParserRule getLabelRule() {
		return getLabelAccess().getRule();
	}

	//StateOrLabel:
	//	State | Label;
	public StateOrLabelElements getStateOrLabelAccess() {
		return (pStateOrLabel != null) ? pStateOrLabel : (pStateOrLabel = new StateOrLabelElements());
	}
	
	public ParserRule getStateOrLabelRule() {
		return getStateOrLabelAccess().getRule();
	}

	//S:
	//	"S" Compare "[" StateOrLabel "]";
	public SElements getSAccess() {
		return (pS != null) ? pS : (pS = new SElements());
	}
	
	public ParserRule getSRule() {
		return getSAccess().getRule();
	}

	//P:
	//	"P" Compare "[" "F" TimeBound StateOrLabel "]" | "P" Compare "[" LEFT=StateOrLabel "U" TimeBound RIGHT=StateOrLabel
	//	"]";
	public PElements getPAccess() {
		return (pP != null) ? pP : (pP = new PElements());
	}
	
	public ParserRule getPRule() {
		return getPAccess().getRule();
	}

	//PG:
	//	"P" Compare "[" "G" "(" LEFT=StateOrLabel "=>" "P" CompareWithoutUnknown "[" "F" TimeBound RIGHT=StateOrLabel "]" ")"
	//	"]";
	public PGElements getPGAccess() {
		return (pPG != null) ? pPG : (pPG = new PGElements());
	}
	
	public ParserRule getPGRule() {
		return getPGAccess().getRule();
	}

	//Compare:
	//	CompareWithoutUnknown | "=?";
	public CompareElements getCompareAccess() {
		return (pCompare != null) ? pCompare : (pCompare = new CompareElements());
	}
	
	public ParserRule getCompareRule() {
		return getCompareAccess().getRule();
	}

	//CompareWithoutUnknown:
	//	">" DECIMAL | "<" DECIMAL | ">=" DECIMAL | "<=" DECIMAL;
	public CompareWithoutUnknownElements getCompareWithoutUnknownAccess() {
		return (pCompareWithoutUnknown != null) ? pCompareWithoutUnknown : (pCompareWithoutUnknown = new CompareWithoutUnknownElements());
	}
	
	public ParserRule getCompareWithoutUnknownRule() {
		return getCompareWithoutUnknownAccess().getRule();
	}

	//TimeBound:
	//	(">=" DECIMAL | "<=" DECIMAL | "[" DECIMAL "," DECIMAL "]")?;
	public TimeBoundElements getTimeBoundAccess() {
		return (pTimeBound != null) ? pTimeBound : (pTimeBound = new TimeBoundElements());
	}
	
	public ParserRule getTimeBoundRule() {
		return getTimeBoundAccess().getRule();
	}

	//DECIMAL:
	//	INT ("." INT)?;
	public DECIMALElements getDECIMALAccess() {
		return (pDECIMAL != null) ? pDECIMAL : (pDECIMAL = new DECIMALElements());
	}
	
	public ParserRule getDECIMALRule() {
		return getDECIMALAccess().getRule();
	}

	//terminal ID:
	//	"^"? ("a".."z" | "A".."Z" | "_") ("a".."z" | "A".."Z" | "_" | "0".."9")*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	} 

	//terminal INT returns ecore::EInt:
	//	"0".."9"+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	} 

	//terminal STRING:
	//	"\"" ("\\" ("b" | "t" | "n" | "f" | "r" | "u" | "\"" | "\'" | "\\") | !("\\" | "\""))* "\"" | "\'" ("\\" ("b" | "t" |
	//	"n" | "f" | "r" | "u" | "\"" | "\'" | "\\") | !("\\" | "\'"))* "\'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	} 

	//terminal ML_COMMENT:
	//	"/ *"->"* /";
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	} 

	//terminal SL_COMMENT:
	//	"//" !("\n" | "\r")* ("\r"? "\n")?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	} 

	//terminal WS:
	//	(" " | "\t" | "\r" | "\n")+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	} 

	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	} 
}
