/**
 *
 * $Id$
 */
package de.uni_stuttgart.iste.cowolf.model.fault_tree.validation;

import de.uni_stuttgart.iste.cowolf.model.fault_tree.BasicEvent;
import de.uni_stuttgart.iste.cowolf.model.fault_tree.ErrorType;
import de.uni_stuttgart.iste.cowolf.model.fault_tree.Root;

/**
 * A sample validator interface for {@link de.uni_stuttgart.iste.cowolf.model.fault_tree.ErrorInstance}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ErrorInstanceValidator {
	boolean validate();

	boolean validateError(BasicEvent value);
	boolean validateType(ErrorType value);
	boolean validateRoot(Root value);
	boolean validateName(String value);
}
