/**
 *
 * $Id$
 */
package de.uni_stuttgart.iste.cowolf.model.fault_tree.validation;

import de.uni_stuttgart.iste.cowolf.model.fault_tree.ErrorInstance;
import de.uni_stuttgart.iste.cowolf.model.fault_tree.FailureInstance;
import de.uni_stuttgart.iste.cowolf.model.fault_tree.FailureType;
import de.uni_stuttgart.iste.cowolf.model.fault_tree.FaultTree;
import de.uni_stuttgart.iste.cowolf.model.fault_tree.IntermediateEvent;

/**
 * A sample validator interface for {@link de.uni_stuttgart.iste.cowolf.model.fault_tree.FailureInstance}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface FailureInstanceValidator {
	boolean validate();

	boolean validateType(FailureType value);
	boolean validateRoot(FaultTree value);
	boolean validatePreviousFailure(FailureInstance value);
	boolean validatePreviousError(ErrorInstance value);
	boolean validateEvent(IntermediateEvent value);
	boolean validateName(String value);
}
