/**
 *
 * $Id$
 */
package de.uni_stuttgart.iste.cowolf.model.fault_tree.validation;

import de.uni_stuttgart.iste.cowolf.model.fault_tree.Event;
import de.uni_stuttgart.iste.cowolf.model.fault_tree.Gate;
import de.uni_stuttgart.iste.cowolf.model.fault_tree.Root;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link de.uni_stuttgart.iste.cowolf.model.fault_tree.Gate}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface GateValidator {
	boolean validate();

	boolean validateId(int value);
	boolean validateInputGates(EList<Gate> value);
	boolean validateInputEvents(EList<Event> value);
	boolean validateOutputGate(Gate value);
	boolean validateOutputEvent(Event value);
	boolean validateRoot(Root value);
}
