/**
 * generated by Xtext
 */
package de.uni_stuttgart.iste.cowolf.model.ctmc.xtext.ui.quickfix;

import org.eclipse.xtext.ui.editor.quickfix.DefaultQuickfixProvider;

/**
 * Custom quickfixes.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#quickfixes
 */
@SuppressWarnings("all")
public class PCTLQuickfixProvider extends DefaultQuickfixProvider {
}
