/*
* generated by Xtext
*/
package de.uni_stuttgart.iste.cowolf.model.ctmc.xtext.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import de.uni_stuttgart.iste.cowolf.model.ctmc.xtext.services.PCTLGrammarAccess;

public class PCTLParser extends AbstractContentAssistParser {
	
	@Inject
	private PCTLGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected de.uni_stuttgart.iste.cowolf.model.ctmc.xtext.ui.contentassist.antlr.internal.InternalPCTLParser createParser() {
		de.uni_stuttgart.iste.cowolf.model.ctmc.xtext.ui.contentassist.antlr.internal.InternalPCTLParser result = new de.uni_stuttgart.iste.cowolf.model.ctmc.xtext.ui.contentassist.antlr.internal.InternalPCTLParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getPctlAccess().getAlternatives(), "rule__Pctl__Alternatives");
					put(grammarAccess.getAtomicAccess().getAlternatives(), "rule__Atomic__Alternatives");
					put(grammarAccess.getJunctionAccess().getAlternatives(), "rule__Junction__Alternatives");
					put(grammarAccess.getStateFormulaAccess().getAlternatives(), "rule__StateFormula__Alternatives");
					put(grammarAccess.getStateFormulaAccess().getAlternatives_0_2(), "rule__StateFormula__Alternatives_0_2");
					put(grammarAccess.getPathFormulaAccess().getAlternatives(), "rule__PathFormula__Alternatives");
					put(grammarAccess.getSteadyStateAccess().getAlternatives_1(), "rule__SteadyState__Alternatives_1");
					put(grammarAccess.getUntilAccess().getAlternatives_1(), "rule__Until__Alternatives_1");
					put(grammarAccess.getCompareProbabilityAccess().getAlternatives_0(), "rule__CompareProbability__Alternatives_0");
					put(grammarAccess.getTimeBoundAccess().getAlternatives(), "rule__TimeBound__Alternatives");
					put(grammarAccess.getTimeBoundAccess().getAlternatives_0_0(), "rule__TimeBound__Alternatives_0_0");
					put(grammarAccess.getStartAccess().getGroup(), "rule__Start__Group__0");
					put(grammarAccess.getCommentedRuleAccess().getGroup(), "rule__CommentedRule__Group__0");
					put(grammarAccess.getStateAccess().getGroup(), "rule__State__Group__0");
					put(grammarAccess.getLabelAccess().getGroup(), "rule__Label__Group__0");
					put(grammarAccess.getNegationAccess().getGroup(), "rule__Negation__Group__0");
					put(grammarAccess.getConjunctionAccess().getGroup(), "rule__Conjunction__Group__0");
					put(grammarAccess.getConjunctionAccess().getGroup_2(), "rule__Conjunction__Group_2__0");
					put(grammarAccess.getDisjunctionAccess().getGroup(), "rule__Disjunction__Group__0");
					put(grammarAccess.getDisjunctionAccess().getGroup_2(), "rule__Disjunction__Group_2__0");
					put(grammarAccess.getStateFormulaAccess().getGroup_0(), "rule__StateFormula__Group_0__0");
					put(grammarAccess.getSteadyStateAccess().getGroup(), "rule__SteadyState__Group__0");
					put(grammarAccess.getQuantifiedProbabilityAccess().getGroup(), "rule__QuantifiedProbability__Group__0");
					put(grammarAccess.getQuantifiedProbabilityAccess().getGroup_0(), "rule__QuantifiedProbability__Group_0__0");
					put(grammarAccess.getProbabilityAccess().getGroup(), "rule__Probability__Group__0");
					put(grammarAccess.getUntilAccess().getGroup(), "rule__Until__Group__0");
					put(grammarAccess.getNextAccess().getGroup(), "rule__Next__Group__0");
					put(grammarAccess.getFutureAccess().getGroup(), "rule__Future__Group__0");
					put(grammarAccess.getGloballyAccess().getGroup(), "rule__Globally__Group__0");
					put(grammarAccess.getImplicationAccess().getGroup(), "rule__Implication__Group__0");
					put(grammarAccess.getCompareProbabilityAccess().getGroup(), "rule__CompareProbability__Group__0");
					put(grammarAccess.getCompareProbabilityAccess().getGroup_0_0(), "rule__CompareProbability__Group_0_0__0");
					put(grammarAccess.getCompareProbabilityAccess().getGroup_0_1(), "rule__CompareProbability__Group_0_1__0");
					put(grammarAccess.getTimeBoundAccess().getGroup_0(), "rule__TimeBound__Group_0__0");
					put(grammarAccess.getTimeBoundAccess().getGroup_0_0_0(), "rule__TimeBound__Group_0_0_0__0");
					put(grammarAccess.getTimeBoundAccess().getGroup_0_0_1(), "rule__TimeBound__Group_0_0_1__0");
					put(grammarAccess.getTimeBoundAccess().getGroup_1(), "rule__TimeBound__Group_1__0");
					put(grammarAccess.getStartAccess().getStartAssignment_0(), "rule__Start__StartAssignment_0");
					put(grammarAccess.getStartAccess().getStartAssignment_1(), "rule__Start__StartAssignment_1");
					put(grammarAccess.getCommentedRuleAccess().getCommentAssignment_0(), "rule__CommentedRule__CommentAssignment_0");
					put(grammarAccess.getCommentedRuleAccess().getRuleAssignment_1(), "rule__CommentedRule__RuleAssignment_1");
					put(grammarAccess.getStateAccess().getNameAssignment_1(), "rule__State__NameAssignment_1");
					put(grammarAccess.getLabelAccess().getNameAssignment_1(), "rule__Label__NameAssignment_1");
					put(grammarAccess.getConjunctionAccess().getRightAssignment_2_2(), "rule__Conjunction__RightAssignment_2_2");
					put(grammarAccess.getDisjunctionAccess().getRightAssignment_2_2(), "rule__Disjunction__RightAssignment_2_2");
					put(grammarAccess.getStateFormulaAccess().getLeftAssignment_0_1(), "rule__StateFormula__LeftAssignment_0_1");
					put(grammarAccess.getStateFormulaAccess().getRightAssignment_0_2_0(), "rule__StateFormula__RightAssignment_0_2_0");
					put(grammarAccess.getStateFormulaAccess().getRightAssignment_0_2_1(), "rule__StateFormula__RightAssignment_0_2_1");
					put(grammarAccess.getStateFormulaAccess().getLeftAssignment_3(), "rule__StateFormula__LeftAssignment_3");
					put(grammarAccess.getUntilAccess().getLeftAssignment_0(), "rule__Until__LeftAssignment_0");
					put(grammarAccess.getUntilAccess().getRightAssignment_3(), "rule__Until__RightAssignment_3");
					put(grammarAccess.getNextAccess().getRightAssignment_2(), "rule__Next__RightAssignment_2");
					put(grammarAccess.getFutureAccess().getRightAssignment_2(), "rule__Future__RightAssignment_2");
					put(grammarAccess.getGloballyAccess().getRightAssignment_2(), "rule__Globally__RightAssignment_2");
					put(grammarAccess.getImplicationAccess().getRightAssignment_1(), "rule__Implication__RightAssignment_1");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			de.uni_stuttgart.iste.cowolf.model.ctmc.xtext.ui.contentassist.antlr.internal.InternalPCTLParser typedParser = (de.uni_stuttgart.iste.cowolf.model.ctmc.xtext.ui.contentassist.antlr.internal.InternalPCTLParser) parser;
			typedParser.entryRuleStart();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public PCTLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(PCTLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
