<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="sequence_diagram" nsURI="http://SequenceDiagram/1.0" nsPrefix="sequence_diagram">
  <eClassifiers xsi:type="ecore:EClass" name="Lifeline" eSuperTypes="../../de.uni_stuttgart.iste.cowolf.model/model/CommonBase.ecore#//IDBase">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tasks" upperBound="-1"
        eType="#//Task" eOpposite="#//Task/lifeline"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Message" abstract="true" eSuperTypes="../../de.uni_stuttgart.iste.cowolf.model/model/CommonBase.ecore#//IDBase">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="messageKind" eType="#//MessageKind"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="message" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="in" lowerBound="1" eType="#//Container"
        eOpposite="#//Container/messages"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Task" eSuperTypes="../../de.uni_stuttgart.iste.cowolf.model/model/CommonBase.ecore#//IDBase">
    <eStructuralFeatures xsi:type="ecore:EReference" name="outgoingMessages" upperBound="-1"
        eType="#//Message" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lifeline" lowerBound="1"
        eType="#//Lifeline" eOpposite="#//Lifeline/tasks"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="from" lowerBound="1" eType="#//MessageBase"
        eOpposite="#//MessageBase/to"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="in" lowerBound="1" eType="#//Container"
        eOpposite="#//Container/tasks"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="MessageKind">
    <eLiterals name="lost" value="1" literal="lost"/>
    <eLiterals name="found" literal="found"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="MessageSortSpecial">
    <eLiterals name="createMessage" literal="createMessage"/>
    <eLiterals name="deleteMessage" value="1" literal="deleteMessage"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="MessageSortNormal">
    <eLiterals name="synchCall" literal="synchCall"/>
    <eLiterals name="asynchCall" value="1" literal="asynchCall"/>
    <eLiterals name="reply" value="2" literal="reply"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LoopBlock" eSuperTypes="#//Block ../../de.uni_stuttgart.iste.cowolf.model/model/CommonBase.ecore#//IDBase #//BlockBase">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="condition" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AltBlock" eSuperTypes="../../de.uni_stuttgart.iste.cowolf.model/model/CommonBase.ecore#//IDBase #//BlockBase">
    <eStructuralFeatures xsi:type="ecore:EReference" name="alternative" lowerBound="2"
        upperBound="-1" eType="#//Alternative" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Alternative" eSuperTypes="#//Block ../../de.uni_stuttgart.iste.cowolf.model/model/CommonBase.ecore#//IDBase">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="condition" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="optBlock" eSuperTypes="#//Block ../../de.uni_stuttgart.iste.cowolf.model/model/CommonBase.ecore#//IDBase #//BlockBase">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="condition" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="topLayer" eSuperTypes="#//Container ../../de.uni_stuttgart.iste.cowolf.model/model/CommonBase.ecore#//IDBase">
    <eStructuralFeatures xsi:type="ecore:EReference" name="lifelines" lowerBound="1"
        upperBound="-1" eType="#//Lifeline" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="loopBlocks" upperBound="-1"
        eType="#//LoopBlock" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="altBlocks" upperBound="-1"
        eType="#//AltBlock" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="optBlocks" upperBound="-1"
        eType="#//optBlock" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="actors" lowerBound="1"
        upperBound="-1" eType="#//Actor" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Container" abstract="true" eSuperTypes="../../de.uni_stuttgart.iste.cowolf.model/model/CommonBase.ecore#//IDBase">
    <eStructuralFeatures xsi:type="ecore:EReference" name="messages" upperBound="-1"
        eType="#//Message" eOpposite="#//Message/in"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tasks" upperBound="-1"
        eType="#//Task" eOpposite="#//Task/in"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Block" abstract="true" eSuperTypes="#//Container ../../de.uni_stuttgart.iste.cowolf.model/model/CommonBase.ecore#//IDBase">
    <eStructuralFeatures xsi:type="ecore:EReference" name="includes" upperBound="-1"
        eType="#//BlockBase" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InitialMessage" eSuperTypes="#//MessageBase ../../de.uni_stuttgart.iste.cowolf.model/model/CommonBase.ecore#//IDBase">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="message" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Actor" eSuperTypes="../../de.uni_stuttgart.iste.cowolf.model/model/CommonBase.ecore#//IDBase">
    <eStructuralFeatures xsi:type="ecore:EReference" name="initialMessages" upperBound="-1"
        eType="#//InitialMessage" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SpecialMessage" eSuperTypes="#//Message ../../de.uni_stuttgart.iste.cowolf.model/model/CommonBase.ecore#//IDBase">
    <eStructuralFeatures xsi:type="ecore:EReference" name="to" lowerBound="1" eType="#//Lifeline"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="messageSort" eType="#//MessageSortSpecial"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NormalMessage" eSuperTypes="#//Message #//MessageBase ../../de.uni_stuttgart.iste.cowolf.model/model/CommonBase.ecore#//IDBase">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="messageSort" eType="#//MessageSortNormal"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MessageBase" abstract="true" eSuperTypes="../../de.uni_stuttgart.iste.cowolf.model/model/CommonBase.ecore#//IDBase">
    <eStructuralFeatures xsi:type="ecore:EReference" name="to" lowerBound="1" eType="#//Task"
        containment="true" eOpposite="#//Task/from"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Sequence" eSuperTypes="../../de.uni_stuttgart.iste.cowolf.model/model/CommonBase.ecore#//IDBase">
    <eStructuralFeatures xsi:type="ecore:EReference" name="topLayer" lowerBound="1"
        eType="#//topLayer" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BlockBase"/>
</ecore:EPackage>
