<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="sequence_diagram" nsURI="http://sequence_diagram/1.0" nsPrefix="sequence_diagram">
  <eClassifiers xsi:type="ecore:EClass" name="Sequence" eSuperTypes="../../org.eclipse.uml2.uml/model/UML.ecore#//Interaction"/>
</ecore:EPackage>
