<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="sequence_diagram" nsURI="http://sequence_diagram/1.0" nsPrefix="sequence_diagram">
  <eClassifiers xsi:type="ecore:EClass" name="Message" eSuperTypes="../../org.eclipse.uml2.uml/model/UML.ecore#//Message ../../de.uni_stuttgart.iste.cowolf.model/model/CommonBase.ecore#//IDBase">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A Message defines a particular communication between Lifelines of an Interaction.&#xA;&lt;p>From package UML::Interactions.&lt;/p>"/>
    </eAnnotations>
    <eAnnotations source="duplicates">
      <contents xsi:type="ecore:EOperation" name="isDistinguishableFrom" ordered="false"
          lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//Boolean">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The query isDistinguishableFrom() specifies that any two Messages may coexist in the same Namespace, regardless of their names.&#xA;result = (true)&#xA;&lt;p>From package UML::Interactions.&lt;/p>"/>
        </eAnnotations>
        <eAnnotations source="redefines" references="../../org.eclipse.uml2.uml/model/UML.ecore#//NamedElement/isDistinguishableFrom"/>
        <eParameters name="n" ordered="false" lowerBound="1" eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//NamedElement"/>
        <eParameters name="ns" ordered="false" lowerBound="1" eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Namespace"/>
      </contents>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Lifeline" eSuperTypes="../../org.eclipse.uml2.uml/model/UML.ecore#//Lifeline ../../de.uni_stuttgart.iste.cowolf.model/model/CommonBase.ecore#//IDBase">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A Lifeline represents an individual participant in the Interaction. While parts and structural features may have multiplicity greater than 1, Lifelines represent only one interacting entity.&#xA;&lt;p>From package UML::Interactions.&lt;/p>"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExecutionSpecification" abstract="true"
      eSuperTypes="../../org.eclipse.uml2.uml/model/UML.ecore#//ExecutionSpecification ../../de.uni_stuttgart.iste.cowolf.model/model/CommonBase.ecore#//IDBase">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="An ExecutionSpecification is a specification of the execution of a unit of Behavior or Action within the Lifeline. The duration of an ExecutionSpecification is represented by two OccurrenceSpecifications, the start OccurrenceSpecification and the finish OccurrenceSpecification.&#xA;&lt;p>From package UML::Interactions.&lt;/p>"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Actor" eSuperTypes="../../org.eclipse.uml2.uml/model/UML.ecore#//Actor ../../de.uni_stuttgart.iste.cowolf.model/model/CommonBase.ecore#//IDBase">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="An Actor specifies a role played by a user or any other system that interacts with the subject.&#xA;&lt;p>From package UML::UseCases.&lt;/p>"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SdInteraction" eSuperTypes="../../org.eclipse.uml2.uml/model/UML.ecore#//Interaction ../../de.uni_stuttgart.iste.cowolf.model/model/CommonBase.ecore#//IDBase">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="An Interaction is a unit of Behavior that focuses on the observable exchange of information between connectable elements.&#xA;&lt;p>From package UML::Interactions.&lt;/p>"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Package" eSuperTypes="../../org.eclipse.uml2.uml/model/UML.ecore#//Package"/>
</ecore:EPackage>
