<?xml version="1.0" encoding="ISO-8859-1"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore"
	name="LQN" nsURI="http://LQN/1.0" nsPrefix="lqn">
	<eClassifiers xsi:type="ecore:EClass" name="LQN"
		eSuperTypes="../../de.uni_stuttgart.iste.cowolf.model/model/CommonBase.ecore#//IDBase">
		<eStructuralFeatures xsi:type="ecore:EAttribute"
			name="name" ordered="false" unique="false" lowerBound="1"
			eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" />
		<eStructuralFeatures xsi:type="ecore:EAttribute"
			name="comment" ordered="false" unique="false" lowerBound="1"
			eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" />
		<eStructuralFeatures xsi:type="ecore:EAttribute"
			name="author" ordered="false" unique="false" lowerBound="1"
			eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" />
		<eStructuralFeatures xsi:type="ecore:EReference"
			name="created_On" ordered="false" lowerBound="1" eType="#//Date"
			containment="true" />
		<eStructuralFeatures xsi:type="ecore:EReference"
			name="modified_On" ordered="false" lowerBound="1" eType="#//Date"
			containment="true" />
		<eStructuralFeatures xsi:type="ecore:EReference"
			name="task" ordered="false" lowerBound="1" upperBound="-1" eType="#//Task"
			containment="true" eOpposite="#//Task/lqn" />
		<eStructuralFeatures xsi:type="ecore:EReference"
			name="processor" ordered="false" lowerBound="1" upperBound="-1"
			eType="#//Processor" containment="true" eOpposite="#//Processor/lqn" />
	</eClassifiers>
	<eClassifiers xsi:type="ecore:EClass" name="Task"
		eSuperTypes="../../de.uni_stuttgart.iste.cowolf.model/model/CommonBase.ecore#//IDBase">
		<eStructuralFeatures xsi:type="ecore:EAttribute"
			name="name" ordered="false" unique="false" lowerBound="1"
			eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" />
		<eStructuralFeatures xsi:type="ecore:EAttribute"
			name="type" ordered="false" unique="false" lowerBound="1" eType="#//TaskType" />
		<eStructuralFeatures xsi:type="ecore:EAttribute"
			name="priority" ordered="false" unique="false" lowerBound="1"
			eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" />
		<eStructuralFeatures xsi:type="ecore:EAttribute"
			name="mutliplicity" ordered="false" unique="false" lowerBound="1"
			eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" />
		<eStructuralFeatures xsi:type="ecore:EAttribute"
			name="replicas" ordered="false" unique="false" lowerBound="1"
			eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" />
		<eStructuralFeatures xsi:type="ecore:EReference"
			name="entry" ordered="false" lowerBound="1" upperBound="-1" eType="#//Entry"
			containment="true" eOpposite="#//Entry/task" />
		<eStructuralFeatures xsi:type="ecore:EReference"
			name="processor" ordered="false" lowerBound="1" eType="#//Processor"
			eOpposite="#//Processor/task" />
		<eStructuralFeatures xsi:type="ecore:EReference"
			name="lqn" ordered="false" lowerBound="1" eType="#//LQN" eOpposite="#//LQN/task" />
		<eStructuralFeatures xsi:type="ecore:EReference"
			name="activity" ordered="false" lowerBound="1" upperBound="-1"
			eType="#//Activity" eOpposite="#//Activity/task" />
	</eClassifiers>
	<eClassifiers xsi:type="ecore:EClass" name="Processor"
		eSuperTypes="../../de.uni_stuttgart.iste.cowolf.model/model/CommonBase.ecore#//IDBase">
		<eStructuralFeatures xsi:type="ecore:EAttribute"
			name="name" ordered="false" unique="false" lowerBound="1"
			eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" />
		<eStructuralFeatures xsi:type="ecore:EAttribute"
			name="scheduling" ordered="false" unique="false" lowerBound="1"
			eType="#//SchedulingType" />
		<eStructuralFeatures xsi:type="ecore:EAttribute"
			name="mutliplicity" ordered="false" unique="false" lowerBound="1"
			eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" />
		<eStructuralFeatures xsi:type="ecore:EAttribute"
			name="replicas" ordered="false" unique="false" lowerBound="1"
			eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" />
		<eStructuralFeatures xsi:type="ecore:EAttribute"
			name="spped" ordered="false" unique="false" lowerBound="1"
			eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" />
		<eStructuralFeatures xsi:type="ecore:EReference"
			name="task" ordered="false" lowerBound="1" eType="#//Task" eOpposite="#//Task/processor" />
		<eStructuralFeatures xsi:type="ecore:EReference"
			name="lqn" ordered="false" lowerBound="1" eType="#//LQN" eOpposite="#//LQN/processor" />
	</eClassifiers>
	<eClassifiers xsi:type="ecore:EClass" name="Entry"
		eSuperTypes="../../de.uni_stuttgart.iste.cowolf.model/model/CommonBase.ecore#//IDBase">
		<eStructuralFeatures xsi:type="ecore:EAttribute"
			name="name" ordered="false" unique="false" lowerBound="1"
			eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" />
		<eStructuralFeatures xsi:type="ecore:EAttribute"
			name="num_Phase" ordered="false" unique="false" lowerBound="1"
			eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" />
		<eStructuralFeatures xsi:type="ecore:EAttribute"
			name="arrival_Rate" ordered="false" unique="false" lowerBound="1"
			eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" />
		<eStructuralFeatures xsi:type="ecore:EReference"
			name="contained_In" ordered="false" lowerBound="1" eType="#//Task"
			containment="true" />
		<eStructuralFeatures xsi:type="ecore:EReference"
			name="replay_To" ordered="false" lowerBound="1" eType="#//Entry"
			containment="true" />
		<eStructuralFeatures xsi:type="ecore:EReference"
			name="callreceives" ordered="false" lowerBound="1" eType="#//Call"
			eOpposite="#//Call/entryreceives" />
		<eStructuralFeatures xsi:type="ecore:EReference"
			name="callsends" ordered="false" lowerBound="1" eType="#//Call"
			eOpposite="#//Call/entrysends" />
		<eStructuralFeatures xsi:type="ecore:EReference"
			name="phase" ordered="false" lowerBound="1" upperBound="-1" eType="#//Phase"
			eOpposite="#//Phase/entry" />
		<eStructuralFeatures xsi:type="ecore:EReference"
			name="activity" ordered="false" eType="#//Activity" containment="true"
			eOpposite="#//Activity/entry" />
		<eStructuralFeatures xsi:type="ecore:EReference"
			name="task" ordered="false" lowerBound="1" eType="#//Task" eOpposite="#//Task/entry" />
	</eClassifiers>
	<eClassifiers xsi:type="ecore:EClass" name="Phase"
		eSuperTypes="../../de.uni_stuttgart.iste.cowolf.model/model/CommonBase.ecore#//IDBase">
		<eStructuralFeatures xsi:type="ecore:EAttribute"
			name="number" ordered="false" unique="false" lowerBound="1"
			eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" />
		<eStructuralFeatures xsi:type="ecore:EAttribute"
			name="type" ordered="false" unique="false" lowerBound="1" eType="#//PhaseType" />
		<eStructuralFeatures xsi:type="ecore:EAttribute"
			name="think_Time" ordered="false" unique="false" lowerBound="1"
			eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" />
		<eStructuralFeatures xsi:type="ecore:EAttribute"
			name="execution_Demand" ordered="false" unique="false" lowerBound="1"
			eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" />
		<eStructuralFeatures xsi:type="ecore:EAttribute"
			name="COV" ordered="false" unique="false" lowerBound="1"
			eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" />
		<eStructuralFeatures xsi:type="ecore:EReference"
			name="entry" ordered="false" lowerBound="1" eType="#//Entry"
			eOpposite="#//Entry/phase" />
		<eStructuralFeatures xsi:type="ecore:EReference"
			name="activity" ordered="false" lowerBound="1" eType="#//Activity"
			eOpposite="#//Activity/phase" />
	</eClassifiers>
	<eClassifiers xsi:type="ecore:EClass" name="Activity"
		eSuperTypes="../../de.uni_stuttgart.iste.cowolf.model/model/CommonBase.ecore#//IDBase">
		<eStructuralFeatures xsi:type="ecore:EAttribute"
			name="name" ordered="false" unique="false" lowerBound="1"
			eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" />
		<eStructuralFeatures xsi:type="ecore:EAttribute"
			name="arrival_Rate" ordered="false" unique="false" lowerBound="1"
			eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" />
		<eStructuralFeatures xsi:type="ecore:EReference"
			name="contained_In" ordered="false" lowerBound="1" eType="#//Task"
			containment="true" />
		<eStructuralFeatures xsi:type="ecore:EReference"
			name="replay_To" ordered="false" lowerBound="1" eType="#//Entry"
			containment="true" />
		<eStructuralFeatures xsi:type="ecore:EReference"
			name="linkPrecedes" ordered="false" lowerBound="1" upperBound="-1"
			eType="#//Link" eOpposite="#//Link/activityPrecedes" />
		<eStructuralFeatures xsi:type="ecore:EReference"
			name="linkfollows" ordered="false" lowerBound="1" upperBound="-1"
			eType="#//Link" eOpposite="#//Link/activityfollows" />
		<eStructuralFeatures xsi:type="ecore:EReference"
			name="call" ordered="false" upperBound="-1" eType="#//Call"
			eOpposite="#//Call/activity" />
		<eStructuralFeatures xsi:type="ecore:EReference"
			name="phase" ordered="false" lowerBound="1" eType="#//Phase"
			eOpposite="#//Phase/activity" />
		<eStructuralFeatures xsi:type="ecore:EReference"
			name="entry" ordered="false" lowerBound="1" eType="#//Entry"
			eOpposite="#//Entry/activity" />
		<eStructuralFeatures xsi:type="ecore:EReference"
			name="task" ordered="false" lowerBound="1" eType="#//Task" eOpposite="#//Task/activity" />
	</eClassifiers>
	<eClassifiers xsi:type="ecore:EClass" name="Link"
		eSuperTypes="../../de.uni_stuttgart.iste.cowolf.model/model/CommonBase.ecore#//IDBase">
		<eStructuralFeatures xsi:type="ecore:EAttribute"
			name="type" ordered="false" unique="false" lowerBound="1" eType="#//LinkType" />
		<eStructuralFeatures xsi:type="ecore:EAttribute"
			name="mean_Links" ordered="false" unique="false" lowerBound="1"
			eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" />
		<eStructuralFeatures xsi:type="ecore:EReference"
			name="fromActivity" ordered="false" lowerBound="1" eType="#//Activity"
			containment="true" />
		<eStructuralFeatures xsi:type="ecore:EReference"
			name="toActivity" ordered="false" lowerBound="1" eType="#//Activity"
			containment="true" />
		<eStructuralFeatures xsi:type="ecore:EReference"
			name="activityPrecedes" ordered="false" lowerBound="1" eType="#//Activity"
			eOpposite="#//Activity/linkPrecedes" />
		<eStructuralFeatures xsi:type="ecore:EReference"
			name="activityfollows" ordered="false" lowerBound="1" eType="#//Activity"
			eOpposite="#//Activity/linkfollows" />
	</eClassifiers>
	<eClassifiers xsi:type="ecore:EClass" name="CallPhase"
		eSuperTypes="../../de.uni_stuttgart.iste.cowolf.model/model/CommonBase.ecore#//IDBase">
		<eStructuralFeatures xsi:type="ecore:EAttribute"
			name="mean_Calls" ordered="false" unique="false" lowerBound="1"
			eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" />
		<eStructuralFeatures xsi:type="ecore:EReference"
			name="refers_To" ordered="false" lowerBound="1" eType="#//Phase"
			containment="true" />
		<eStructuralFeatures xsi:type="ecore:EReference"
			name="call" ordered="false" lowerBound="1" upperBound="-1" eType="#//Call"
			eOpposite="#//Call/callPhase" />
	</eClassifiers>
	<eClassifiers xsi:type="ecore:EClass" name="Call"
		eSuperTypes="../../de.uni_stuttgart.iste.cowolf.model/model/CommonBase.ecore#//IDBase">
		<eStructuralFeatures xsi:type="ecore:EReference"
			name="toEntry" ordered="false" lowerBound="1" eType="#//Entry"
			containment="true" />
		<eStructuralFeatures xsi:type="ecore:EAttribute"
			name="num_Phases" ordered="false" unique="false" lowerBound="1"
			eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" />
		<eStructuralFeatures xsi:type="ecore:EAttribute"
			name="type" ordered="false" unique="false" lowerBound="1" eType="#//CallType" />
		<eStructuralFeatures xsi:type="ecore:EReference"
			name="callPhase" ordered="false" lowerBound="1" upperBound="-1"
			eType="#//CallPhase" eOpposite="#//CallPhase/call" />
		<eStructuralFeatures xsi:type="ecore:EReference"
			name="activity" ordered="false" lowerBound="1" eType="#//Activity"
			eOpposite="#//Activity/call" />
		<eStructuralFeatures xsi:type="ecore:EReference"
			name="entryreceives" ordered="false" eType="#//Entry" eOpposite="#//Entry/callreceives" />
		<eStructuralFeatures xsi:type="ecore:EReference"
			name="entrysends" ordered="false" eType="#//Entry" eOpposite="#//Entry/callsends" />
	</eClassifiers>
	<eClassifiers xsi:type="ecore:EClass" name="EntryCall"
		eSuperTypes="#//Call">
		<eStructuralFeatures xsi:type="ecore:EReference"
			name="from_Entry" ordered="false" lowerBound="1" eType="#//Entry"
			containment="true" />
	</eClassifiers>
	<eClassifiers xsi:type="ecore:EClass" name="ActivityCall"
		eSuperTypes="#//Call">
		<eStructuralFeatures xsi:type="ecore:EReference"
			name="fromActivity" ordered="false" lowerBound="1" eType="#//Activity"
			containment="true" />
	</eClassifiers>
	<eClassifiers xsi:type="ecore:EClass" name="Date"
		eSuperTypes="../../de.uni_stuttgart.iste.cowolf.model/model/CommonBase.ecore#//IDBase">
		<eStructuralFeatures xsi:type="ecore:EAttribute"
			name="day" ordered="false" unique="false" lowerBound="1"
			eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" />
		<eStructuralFeatures xsi:type="ecore:EAttribute"
			name="month" ordered="false" unique="false" lowerBound="1"
			eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" />
		<eStructuralFeatures xsi:type="ecore:EAttribute"
			name="year" ordered="false" unique="false" lowerBound="1"
			eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" />
	</eClassifiers>
	<eClassifiers xsi:type="ecore:EEnum" name="SchedulingType">
		<eLiterals name="FCFS" value="1" />
		<eLiterals name="preemptive_Priority" value="2" />
		<eLiterals name="head_of_line" value="3" />
		<eLiterals name="random" value="4" />
	</eClassifiers>
	<eClassifiers xsi:type="ecore:EEnum" name="PhaseType">
		<eLiterals name="stochastic" value="1" />
		<eLiterals name="deterministic" value="2" />
	</eClassifiers>
	<eClassifiers xsi:type="ecore:EEnum" name="CallType">
		<eLiterals name="synchronous" value="1" />
		<eLiterals name="asynchronous" value="2" />
		<eLiterals name="forwording" value="3" />
	</eClassifiers>
	<eClassifiers xsi:type="ecore:EEnum" name="LinkType">
		<eLiterals name="and_Fork" value="1" />
		<eLiterals name="and_join" value="2" />
		<eLiterals name="basic" value="3" />
		<eLiterals name="or_Fork" value="4" />
		<eLiterals name="or_join" value="5" />
	</eClassifiers>
	<eClassifiers xsi:type="ecore:EEnum" name="TaskType">
		<eLiterals name="a_reference" value="1" />
		<eLiterals name="non_reference" value="2" />
	</eClassifiers>
</ecore:EPackage>