/**
 *
 * $Id$
 */
package de.uni_stuttgart.iste.cowolf.model.statechart.Statechart.validation;

import de.uni_stuttgart.iste.cowolf.model.statechart.Statechart.Event;
import de.uni_stuttgart.iste.cowolf.model.statechart.Statechart.StateMachine;
import de.uni_stuttgart.iste.cowolf.model.statechart.Statechart.Transition;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link de.uni_stuttgart.iste.cowolf.model.statechart.Statechart.State}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface StateValidator {
	boolean validate();

	boolean validateState_container(StateMachine value);
	boolean validateInternalTransitions(EList<Transition> value);
	boolean validateDeferrableEvents(EList<Event> value);
}
